// react-app/src/App.js
import React, { useEffect, useState } from "react";
import { load } from "web-component-load";
import "./App.css";

function App() {
  const [reactInputValue, setReactInputValue] = useState("");
  const [angularInputValue, setAngularInputValue] = useState("");

  useEffect(() => {
    load("http://localhost:4200");
  }, []);

  document.addEventListener(
    "angular-input-event",
    function (e) {
      setAngularInputValue(e.detail);
    },
    { capture: true }
  );

  return (
    <div className="app">
      <div className="react-app-container">
        <h2>
          <b>React App</b>
        </h2>
        <p>
          Value from Angular Component: <strong>{angularInputValue}</strong>
        </p>
        <div>
          <input
            onChange={(e) => setReactInputValue(e.target.value)}
            value={reactInputValue}
          />
        </div>
      </div>

      <div>
        <angular-component react-value={reactInputValue} />
      </div>
    </div>
  );
}

export default App;

// angular-elements-app/src/app/app.component.ts
import { DOCUMENT } from '@angular/common';
import { Component, Inject, Input } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  @Input() reactValue = '';
  inputValue = '';

  constructor(@Inject(DOCUMENT) private document: Document) {}

  onKey(event: any): void {
    this.inputValue = event.target.value;
    this.document.dispatchEvent(
      new CustomEvent('angular-input-event', { detail: event.target.value })
    );
  }
}

<div class="angular-app-container">
  <h2><b>Angular Component</b></h2>
  <p>
    Value from React App: <strong>{{ reactValue }}</strong>
  </p>
  <input (keyup)="onKey($event)" />
</div>
